#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: clickhouse-cli

Usage:
  clickhouse-cli"
  exit 1
}

ARGS=($@)
CLICKHOUSE_ADMIN_PASSWORD_ENV='$CLICKHOUSE_ADMIN_PASSWORD'
shift
PARAMS="${*@Q}"
if _is_standalone; then
  docker exec -it deltafi-clickhouse bash -c "clickhouse-client --password ${CLICKHOUSE_ADMIN_PASSWORD_ENV} -d deltafi ${PARAMS}"
else
  POD=$(${KUBECTL_BIN} get pod -l app.kubernetes.io/name=clickhouse -o jsonpath="{.items[0].metadata.name}")
  ${KUBECTL_BIN} exec -it "${POD}" --container clickhouse -- bash -c "clickhouse-client --password ${CLICKHOUSE_ADMIN_PASSWORD_ENV} -d deltafi ${PARAMS}"
fi
