#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

_command_check() {
  command -v $1 &> /dev/null || _exit_1 echo "Command '$@' is not installed. This command cannot execute."
}

_command_check ruby
_command_check jq

cli_help_command() {
  echo "
Command: export-config

Usage:
  export-config"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

RESULT=$(deltafi query "query { exportConfigAsYaml }")
echo "$RESULT" | jq '.data.exportConfigAsYaml' | ruby -ryaml -e 'puts YAML.safe_load(ARGF.read).to_yaml'
