#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: export-enrich-plan

Usage:
  export-enrich-plan FLOW_PLAN_NAME"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

PLANNAME=${ARGS[@]:1}
[[ ${#ARGS[@]} -lt 2 ]] && cli_help_command

QUERY="fragment ActionFields on ActionConfiguration {
          name
          actionType
          type
          parameters
        }

        query {
          getEnrichFlowPlan(planName: \"$PLANNAME\") {
            name
            type
            description
            sourcePlugin {
              groupId
              artifactId
              version
            }
            domainActions {
              ... ActionFields
              requiresDomains
            }
            enrichActions {
              ... ActionFields
              requiresDomains
              requiresEnrichments
              requiresMetadataKeyValues {
                key
                value
              }
            }
          }
        }
        "

RESULT=$(deltafi query "$QUERY")
DGS_ERRORS=$(echo $RESULT | jq -r "select(.errors) | .errors[] | .message")
if [[ "$DGS_ERRORS" != "" ]]; then
  cli_log "${red}${BASENAME}: Failed to export enrich flow plan: $PLANNAME${normal}"
  echo -e "${red}Error: ${DGS_ERRORS}${normal}"
else
  echo "$RESULT" | jq '.data.getEnrichFlowPlan'
fi
