#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: install

Usage:
  install [OPTIONS] [helm flags]

Options:
  -h, --help        Show help"
  exit 1
}

TMPFILE="/tmp/.deltafi-install.$$"

cleanup() {
  rm -f $TMPFILE
  exit
}

trap cleanup INT

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    *)
      POSITIONAL+=("$1")
      shift
      ;;
  esac
done
set -- "${POSITIONAL[@]}"

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

_base64() {
  local TEMPFILE
  if _tool_exists mktemp; then
    TEMPFILE=$(mktemp)
  else
    TEMPFILE=/tmp/base64.foo
    touch $TEMPFILE
  fi

  local BASE64_ARGS=""
  if base64 -i "$TEMPFILE" -w0 > /dev/null 2>&1; then
    BASE64_ARGS="-w0"
  fi

  rm -f "$TEMPFILE"
  base64 $BASE64_ARGS
}

_k8s_add_namespace() {
  local ns=$1
  if ! ${KUBECTL_BIN} get namespace "$ns" > /dev/null 2>&1 ; then
    cat <<EOF | ${KUBECTL_BIN} apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: $ns
EOF
    cli_log "Created namespace $ns"
  fi
}

_k8s_add_secret() {
  local name=$1
  shift
  if ! ${KUBECTL_BIN} describe secret "$name" 2>&1 | grep "$1" > /dev/null; then
    ${KUBECTL_BIN} delete secret "$name" 2>&1
    cli_log "Removed defunct secret $name"
  fi

  if ! ${KUBECTL_BIN} get secret "$name" > /dev/null 2>&1; then
    cat <<EOF | ${KUBECTL_BIN} apply -f -
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: $name
  namespace: deltafi
data:
$(while (( "$#" )); do
local pass
pass=$(printf '%s' "$2" | _base64)
echo "  $1: $pass"
shift 2
done)
EOF
    cli_log "Created secret $name"
  fi
}

_random_password() {
  local size=${1:-20}
  printf '%s%s%s' "$(printf '%s' $RANDOM | md5sum | head -c 20)" "$(printf '%s' $RANDOM | md5sum | head -c 20)" "$(printf '%s' $RANDOM | md5sum | head -c 20)" | _base64 | head -c "$size"
}

_k8s_prerequisites() {
  cli_log "Initializing k8s prerequisites"
  _k8s_add_namespace deltafi
  _k8s_add_secret mongodb-passwords mongodb-password "$(_random_password 20)" mongodb-root-password "$(_random_password 20)"
  _k8s_add_secret minio-keys rootUser "deltafi" rootPassword "$(_random_password 40)"
  _k8s_add_secret redis-password redis-password "$(_random_password 16)"
  _k8s_add_secret config-repo-secret config-token "$(_random_password 16)"
}

_k8s_install() {
  _k8s_prerequisites

  if [[ ! -f "${DELTAFICLI_CHART_PATH}/Chart.lock" ]]; then
    cli_log "Executing helm dependencies"
    cd $DELTAFICLI_CHART_PATH
    helm dependencies build
    cd - > /dev/null
  fi

  ORIG_CORE_POD=$(${KUBECTL_BIN} get pods | grep "^deltafi-core-[a-f0-9]\{10\}-" | head -n 1 | cut -d' ' -f1)

  if [[ -n "${ORIG_CORE_POD}" ]]; then
    _pre_upgrade_tasks
  fi

  helm upgrade --install --wait \
    --values $DELTAFICLI_CHART_PATH/values.yaml \
    --namespace $DELTAFICLI_K8S_NAMESPACE $DELTAFICLI_PROJECT_NAME $DELTAFICLI_CHART_PATH \
    --create-namespace --timeout 10m ${ARGS[@]:1}

  HELM_RETURN_CODE=$?
  [[ "$HELM_RETURN_CODE" != "0" ]] && exit $HELM_RETURN_CODE

  NEW_CORE_POD=$(${KUBECTL_BIN} get pods | grep "^deltafi-core-[a-f0-9]\{10\}-" | head -n 1 | cut -d' ' -f1)

  if ! [ "${ORIG_CORE_POD}" = "${NEW_CORE_POD}" ]; then
    _run_migrations
  fi
}

_compose_install() {
  core_finder="docker ps --filter name=deltafi-core$ -q"
  ORIG_CORE_CONTAINER=$(${core_finder})

  if [[ -n "${ORIG_CORE_CONTAINER}" ]]; then
    _pre_upgrade_tasks
  fi

  "${DELTAFICLI_COMPOSE_PATH}"/compose start ${ARGS[@]:1}


  NEW_CORE_CONTAINER=$(${core_finder})

  if ! [ "${ORIG_CORE_CONTAINER}" = "${NEW_CORE_CONTAINER}" ]; then
    _run_migrations
  fi
}

_pre_upgrade_tasks() {
  cli_log "Creating a snapshot"
  version=$( cat "${DELTAFICLI_WORKDIR}/VERSION")
  message="Starting upgrade from DeltaFi $(deltafi version) to version ${version}"
  deltafi event create -q -s "cli" --success --notification "$message"
  snapshot_file="pre-upgrade-to-${version}-$(date +%s).json"
  deltafi system-snapshot create "$message" > "${snapshot_file}"
}

_run_migrations() {
  cli_log "Running migrations"
  deltafi event create -q -s "cli" "Running Mongo migrations"
  MONGO_RESULTS=$(deltafi mongo-migrate | sed -e 's|>>|\\n* |g')
  deltafi event create -q -s "cli" --success "Completed Mongo migrations" --content "${MONGO_RESULTS}"

  deltafi event create -q -s "cli" --success --notification "Installed DeltaFi version $( cat "${DELTAFICLI_WORKDIR}/VERSION")"
}

cli_log "Installing DeltaFi"

if _is_standalone; then
  _compose_install
else
  _k8s_install
fi

cli_log "DeltaFi install complete"
