#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: list-flows

Usage:
  list-flows

Options:
  -h, --help  Show help"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " || " ${ARGS[@]} " =~ " -h " ]] && cli_help_command

FIELDS="{ name flowStatus {state}}"
QUERY="query { getAllFlows { transform $FIELDS normalize $FIELDS enrich $FIELDS egress $FIELDS}}"
RESULT=$(deltafi query "$QUERY")

print_flows() {
  FLOW_TYPE=$(tr '[:lower:]' '[:upper:]' <<< ${1:0:1})${1:1}
  echo "$RESULT" | jq -r "([\"${FLOW_TYPE} Flow\", \"State\"] | (., map(length*\"=\"))), (.data.getAllFlows.$1[] | [.name, .flowStatus.state]) | @tsv" | column -ts $'\t'
}

DGS_ERRORS=$(echo $RESULT | jq -r "select(.errors) | .errors[] | .message")
if [[ "$DGS_ERRORS" != "" ]]; then
  cli_log "${red}${BASENAME}: Failed to get the list of flow plans${normal}"
  echo -e "${red}Error: ${DGS_ERRORS}${normal}"
else
  print_flows "transform"
  echo
  print_flows "normalize"
  echo
  print_flows "enrich"
  echo
  print_flows "egress"
fi