#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: load-plans

Usage:
  load-plans <plan_or_flows_dir>
  
Options:
  -h, --help  Show help"
  exit 1
}

TMPFILE="/tmp/.deltafi-load-plans.$$"

cleanup() {
  rm -f $TMPFILE
  exit
}

trap cleanup INT

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h|--help)
      cli_help_command
      shift # past argument
      ;;
    *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters
ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command
[[ ${#ARGS[@]} -lt 2 ]] && cli_help_command


FLOWS_DIRECTORY=${ARGS[1]}
if [ ! -e "${FLOWS_DIRECTORY}" ]; then
    cli_log "${red}${FLOWS_DIRECTORY}: Flow plan or flows directory not found${normal}"
  exit 1
fi

if [ -d "${FLOWS_DIRECTORY}" ]; then
  FLOWS_DIRECTORY=$(cd ${FLOWS_DIRECTORY} && pwd)
fi

DELTAFI_DGS=$(deltafi serviceip deltafi-core-service)

read_file() {
  FLOW_PLAN_FILE="$@"
  if [ ! -f "${FLOW_PLAN_FILE}" ]; then
    cli_log "${yellow}${FLOW_PLAN_FILE}: No such file${normal}"
    return 1
  fi

  JSON=$(cat "${FLOW_PLAN_FILE}")

  echo "${JSON}"
}

execute_graphql() {
  truncate -s 0 ${TMPFILE}

  local POST_QUERY="$@"

  local RESPONSE_CODE=$(curl -s -X POST -o ${TMPFILE} -w "%{http_code}" -H "Content-Type: application/json" -H "${PERMISSION}" -H "${CLI_USER}" -d "${POST_QUERY}" http://${DELTAFI_DGS}/graphql)

  if [[ "${RESPONSE_CODE}" != "200" ]]; then
    echo -e "${RESPONSE_CODE} Error: $(cat ${TMPFILE})"
    return 1
  else
    ERRORS=$(cat ${TMPFILE} | jq "select(.errors) | .errors[] | .message")
    if [[ "${ERRORS}" != "" ]]; then
      echo -e "${ERRORS}"
      return 1
    else
      cat "${TMPFILE}"
      return 0
    fi
  fi
}

load_variables() {
  local VARIABLES_FILE="$@"
  local BASENAME="$(basename "${VARIABLES_FILE}")"
  local JSON=$(read_file "${VARIABLES_FILE}")

  local VARIABLES="{\"variables\": ${JSON} }"
  local QUERY="mutation(\$variables: [VariableInput]!) { savePluginVariables(variables: \$variables)}"
  local POST_QUERY="{ \"query\": \"${QUERY}\",\"variables\":${VARIABLES}}"

  MUTATION_RESPONSE=$(execute_graphql "${POST_QUERY}")
  MUTATION_RETURN_CODE=$?

  if [[ "${MUTATION_RETURN_CODE}" == "0" ]]; then
    cli_log "Successfully loaded variables from file ${cyan}${BASENAME}${normal}"
  else
    cli_log "${red}${BASENAME}: Loading variables failed${normal}"
    echo -e "${red}${MUTATION_RESPONSE}${normal}"
    # if the variables can't be loaded do not load the flow plans
    exit 1
  fi
}

load_plan() {
  local FLOW_PLAN_FILE="$@"
  local BASENAME="$(basename ${FLOW_PLAN_FILE})"
  local JSON=$(read_file "${FLOW_PLAN_FILE}")

  local VARIABLES="{\"flowPlan\": ${JSON} }"

  if [[ "${JSON}" == *"\"type\": \"INGRESS\""* || "${JSON}" == *"\"type\": \"NORMALIZE\""* ]]; then
    local LOAD_TYPE="normalize flow plan"
    local OPERATION_NAME="saveNormalizeFlowPlan"
    local QUERY="mutation(\$flowPlan: NormalizeFlowPlanInput!) {saveNormalizeFlowPlan(normalizeFlowPlan: \$flowPlan) { name }}"
  elif [[ "${JSON}" == *"\"type\": \"EGRESS\""* ]]; then
    local LOAD_TYPE="egress flow plan"
    local OPERATION_NAME="saveEgressFlowPlan"
    local QUERY="mutation(\$flowPlan: EgressFlowPlanInput!) {saveEgressFlowPlan(egressFlowPlan: \$flowPlan) { name }}"
  elif [[ "${JSON}" == *"\"type\": \"ENRICH\""* ]]; then
    local LOAD_TYPE="enrich flow plan"
    local OPERATION_NAME="saveEnrichFlowPlan"
    local QUERY="mutation(\$flowPlan: EnrichFlowPlanInput!) {saveEnrichFlowPlan(enrichFlowPlan: \$flowPlan) { name }}"
  elif [[ "${JSON}" == *"\"type\": \"TRANSFORM\""* ]]; then
      local LOAD_TYPE="transform flow plan"
      local OPERATION_NAME="saveTransformFlowPlan"
      local QUERY="mutation(\$flowPlan: TransformFlowPlanInput!) {saveTransformFlowPlan(transformFlowPlan: \$flowPlan) { name }}"
  else
    cli_log "${red}${BASENAME}: Loading flow plan failed, the plan must contain a load or join action, enrich actions, or an egress action${normal}"
    echo -e "${red}Loading flow plan failed, plan must contain a load or join action, enrich actions, or an egress action${normal}"
    return 0
  fi

  local POST_QUERY="{ \"query\": \"${QUERY}\",\"variables\":${VARIABLES}}"

  MUTATION_RESPONSE=$(execute_graphql "${POST_QUERY}")
  MUTATION_RETURN_CODE=$?

  if [[ "${MUTATION_RETURN_CODE}" == "0" ]]; then
    local FLOW_PLAN_NAME=$(echo "${MUTATION_RESPONSE}" | jq -r ".data.${OPERATION_NAME}.name")
    cli_log "Successfully loaded ${LOAD_TYPE} ${FLOW_PLAN_NAME} from file ${cyan}${BASENAME}${normal}"
  else
    cli_log "${red}${BASENAME}: Loading ${LOAD_TYPE} failed${normal}"
    echo -e "${red}${MUTATION_RESPONSE}${normal}"
  fi
}

cli_log "Loading flow plan(s) and/or variables to the system-plugin"

if [[ -d ${FLOWS_DIRECTORY} ]]; then
  if [[ -f ${FLOWS_DIRECTORY}/variables.json ]]; then
    load_variables "${FLOWS_DIRECTORY}/variables.json"
  fi

  for flowFile in "${FLOWS_DIRECTORY}"/*.json; do
    if [[ ! "${flowFile}" =~ "variables.json" ]]; then
      load_plan "$flowFile"
    fi
  done
elif [[ -f ${FLOWS_DIRECTORY} ]]; then
  if [[ "${FLOWS_DIRECTORY}" =~ "variables.json" ]]; then
    load_variables "${FLOWS_DIRECTORY}"
  else
    load_plan "${FLOWS_DIRECTORY}"
  fi
fi

cleanup
