#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: minio-cli

Usage:
  minio-cli

Launch a minio-mc instance that is connected to DeltaFi. Example minio-mc command: 'mc ls deltafi/storage'

Options:
  -h, --help        Show help"
  exit 1
}

ARGS=($@)
[[ "${ARGS[@]}" =~ "--help" || " ${ARGS[@]} " =~ " -h " ]] && cli_help_command

# shellcheck disable=SC2016
minio_mc_spec='{
                 "spec": {
                   "containers": [
                     {
                       "name": "deltafi-minio-cli",
                       "image": "minio/mc:RELEASE.2023-01-28T20-29-38Z",
                       "tty": true,
                       "stdin": true,
                       "command": [
                         "/bin/bash"
                       ],
                       "lifecycle": {
                          "postStart": {
                             "exec": {
                                "command": ["/bin/sh", "-c", "/usr/bin/mc alias set deltafi http://deltafi-minio:9000 $MINIO_ACCESSKEY $MINIO_SECRETKEY"]
                             }
                          }
                       },
                       "env": [
                         {
                           "name": "MINIO_ACCESSKEY",
                           "value": "deltafi"
                         },{
                           "name": "MINIO_SECRETKEY",
                           "valueFrom": {
                             "secretKeyRef": {
                               "name": "minio-keys",
                               "key": "rootPassword"
                             }
                           }
                         }
                       ]
                     }
                   ]
                 }
               }'

if _is_standalone; then
  secret_file="${DELTAFICLI_COMPOSE_PATH}/settings/secrets/minio.env"

  ID=$(docker ps -a --filter name=deltafi-minio-mc -q)
  if [[ -n "${ID}" ]]; then
    docker stop "$ID" > /dev/null
    docker rm "$ID" > /dev/null
  fi

  init_file="${DELTAFICLI_WORKDIR}/commands/minio-mc-init.sh"
  docker run -it --label deltafi-group=minio-cli --name deltafi-minio-mc \
  -v "${init_file}":/minio-mc-init.sh \
  --network=deltafi --env-file "${secret_file}" \
  --entrypoint "/minio-mc-init.sh"  minio/mc:RELEASE.2023-01-28T20-29-38Z
else
  kubectl run deltafi-minio-mc --namespace deltafi -i --tty --rm -q --overrides="$minio_mc_spec" --image=minio-mc
fi