#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: mongo-migrate

Usage:
  mongo-migrate [-f] [[list of files]]

  With no arguments, mongo-migrate will run all migrations that have not yet been executed.
  If migration files are listed, they will be the only ones executed.

  -f    - Force execution of all migrations (or listed migrations)"
  exit 1
}

TMPFILE="/tmp/.ui-config.$$"

cleanup() {
  rm -f $TMPFILE
  exit
}

trap cleanup INT

MIGRATION_DIR="/tmp/migrations"

FILES=()
FORCE=

shift
while [ $# -gt 0 ]; do
  arg="$1"
  [[ "$arg" == "-h" || "$arg" == "--help" ]] && cli_help_command
  if [[ "$arg" == "-f" ]]; then
    FORCE=true
  else
    FILES+=("$arg")
  fi
  shift
done


MONGODB_USERNAME_ENV='$MONGODB_USERNAME'
MONGODB_PASSWORD_ENV='$MONGODB_PASSWORD'

_k8s_mongo_migrate() {
  POD=$(${KUBECTL_BIN} get pod -l app.kubernetes.io/name=mongodb -o jsonpath="{.items[0].metadata.name}")
  ${KUBECTL_BIN} exec -i "${POD}" --container mongodb -- sh -c "rm -rf ${MIGRATION_DIR}"
  ${KUBECTL_BIN} cp --container mongodb "${DELTAFI_DIR}/migrations" "${POD}:/tmp/"

  cli_log "$(${KUBECTL_BIN} exec -i "${POD}" --container mongodb -- sh -c "MIGRATION_PATH=${MIGRATION_DIR} ${FORCE:+MIGRATION_FORCE=true} ${FILES:+MIGRATION_FILES=\"${FILES[*]}\"} mongosh --username ${MONGODB_USERNAME_ENV} --password ${MONGODB_PASSWORD_ENV} --quiet deltafi --file ${MIGRATION_DIR}/runner/run-migrations.js")"
}

_compose_mongo_migrate() {
  docker exec -i -u="$(id -u):$(id -g)" deltafi-mongodb sh -c "rm -rf ${MIGRATION_DIR}"
  docker cp -q "${DELTAFI_DIR}/migrations" deltafi-mongodb:/tmp/

  cli_log "$(docker exec -i deltafi-mongodb sh -c "MIGRATION_PATH=${MIGRATION_DIR} ${FORCE:+MIGRATION_FORCE=true} ${FILES:+MIGRATION_FILES=\"${FILES[*]}\"} mongosh --username ${MONGODB_USERNAME_ENV} --password ${MONGODB_PASSWORD_ENV} --quiet deltafi --file ${MIGRATION_DIR}/runner/run-migrations.js")"
}

if _is_standalone; then
  _compose_mongo_migrate
else
  _k8s_mongo_migrate
fi

cleanup
