#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: mongo-cli

Usage:
  mongo-cli"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

MONGODB_USERNAME_ENV='$MONGODB_USERNAME'
MONGODB_PASSWORD_ENV='$MONGODB_PASSWORD'

if _is_standalone; then
  docker exec -it deltafi-mongodb sh -c "mongo -u ${MONGODB_USERNAME_ENV} --password ${MONGODB_PASSWORD_ENV} deltafi"
else
  POD=$(${KUBECTL_BIN} get pod -l app.kubernetes.io/name=mongodb -o jsonpath="{.items[0].metadata.name}")
  ${KUBECTL_BIN} exec -it ${POD} --container mongodb -- sh -c "mongo -u ${MONGODB_USERNAME_ENV} --password ${MONGODB_PASSWORD_ENV} deltafi"
fi
