#!/usr/bin/env ruby
# frozen_string_literal: true

$stdout.sync = true

$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), '../lib'))

require 'deltafi'

def run_test(test_plan_path)
  test_plan_yaml = YAML.load_file(test_plan_path)
  test_plan = Deltafi::Performance::Test::Plan.new(test_plan_yaml)
  Deltafi.log("${green}Test plan loaded from ${bold}#{File.basename(test_plan_path)}${normal}${green}, starting execution now${normal}")
  test_plan.run
rescue StandardError => e
  puts e.message
  e.backtrace.each { |l| puts l }
end

def cli_help_command
  puts '
Command: performance-test

Usage:
  performance-test TEST_PlAN_FILE'
  exit 1
end

cli_help_command if ARGV.length == 1 || ARGV.include?('--help')

test_plan = ARGV[1]

unless File.readable?(test_plan)
  Deltafi.log("${red}Error: Cannot read the test plan at #{test_plan}${normal}")
  exit 1
end

run_test(test_plan)
