#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: redis-stats

Usage:
  redis-stats"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command
REDIS_PASSWORD_ENV='$REDIS_PASSWORD'

if _is_standalone; then
  docker exec -it deltafi-redis sh -c "redis-cli --no-auth-warning -a $REDIS_PASSWORD_ENV --stat"
else
  ${KUBECTL_BIN} exec -it deltafi-redis-master-0 -- sh -c "redis-cli --no-auth-warning -a $REDIS_PASSWORD_ENV --stat"
fi
