#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: secrets

Usage:
  secrets [NAME]"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

SECRETS=${ARGS[@]:1}

_k8s_secrets() {
  KUBECTL_CMD="${KUBECTL_BIN} get secrets"

  if [ -z ${SECRETS} ]; then
    SECRETS=$(${KUBECTL_CMD} --field-selector type=Opaque  | grep -v "^NAME" | awk '{ print $1 }' | xargs)
  fi

  for SECRET in ${SECRETS}; do
    echo "---- ${SECRET} ----"
    FIELDS=$(${KUBECTL_CMD} ${SECRET} -o json | jq -e '.data | keys | join(" ")' -r)
    for FIELD in ${FIELDS}; do
      VALUE=$(${KUBECTL_CMD} ${SECRET} -o json | jq -e ".data.\"${FIELD}\"" -r | base64 -d)
      printf "%-30s%-4s\n"  "${FIELD}" "${VALUE}";
    done
    echo
  done
}

_print_file() {
  filename=$(basename "${1}")
  echo "---- ${filename%.*} ----"
  while IFS="" read -r line || [ -n "$line" ]
  do
    key=${line%=*}
    value="${line##*=}"
    printf "%-30s%-4s\n"  "${key}" "${value}";
  done < "$1"
  echo
}

_compose_secrets() {
  compose_secret_dir="$DELTAFICLI_COMPOSE_PATH/settings/secrets"
  search="*.env"
  if [ -n "${SECRETS}" ]; then
    if [[ "$SECRETS" == *.env ]]; then
      search="$SECRETS"
    else
      search="$SECRETS*.env"
    fi
  fi

  find "$compose_secret_dir" -name "$search" | while read -r file; do _print_file "$file"; done
}

if _is_standalone; then
  _compose_secrets
else
  _k8s_secrets
fi