#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: versions

Usage:
  versions"
  exit 1
}

TMPFILE="/tmp/.deltafi-versions.$$"

cleanup() {
  rm -f $TMPFILE
  exit
}

trap cleanup INT

# Compatability with GNU sed and BSD sed (MacOS)
_sed_prepend() {
  if sed --help >/dev/null 2>&1
  then # GNU
    sed "1 i\\${@}"
  else # BSD
    sed "1i\\
${@}
"
  fi
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

API_HOST=$(deltafi serviceip deltafi-api-service)
API_URL="http://${API_HOST}/api/v1/versions"

truncate -s 0 ${TMPFILE}
RESPONSE_CODE=$(curl -s --connect-timeout 3 -o ${TMPFILE} -w "%{http_code}" -H "Content-Type: application/json" -H "$PERMISSION" -H "$CLI_USER" "${API_URL}" 2>/dev/null)

if [[ "$RESPONSE_CODE" != "200" ]]; then
  echo -e "\nUnable to communicate with API: ${API_URL}\n"
  exit 1
fi

jq '.versions[] | [(.app, .container, .image.name, .image.tag)] | @csv' "${TMPFILE}" \
  | sort -u | sed 's/\\"//g' | sed 's/"//g' | _sed_prepend '===,=========,=====,===' | _sed_prepend 'App,Container,Image,Tag' | column -t -s ','
