#!/bin/bash

BASE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REGISTRY_PATH="registry.gitlab.com/deltafi/"
VALUES_YAML="$BASE_PATH/deltafi/values.yaml"

function _sed_inplace() {
  local UNAME=$(uname)
  if [[ "$UNAME" == 'Darwin' ]]; then
    sed -i '' $@
  else
    sed -i $@
  fi
}

describe set_local_version "Set version of each docker image to local <version>"
function set_local_version() {
  local version=$1
  [[ -z "$version" ]] && _exit_1 echo "Version must be specified"

  _sed_inplace -e "s|image: .*deltafi/\(.*\):.*|image: \1:$version|" "$VALUES_YAML"
}

describe set_registry_version "Set version of each docker image to <version> in registry.gitlab.com/deltafi/"
function set_registry_version() {
  local version=$1
  [[ -z "$version" ]] && _exit_1 echo "Version must be specified"

  _sed_inplace -e "s|image: .*\(deltafi/.*\):.*|image: ${REGISTRY_PATH}\1:$version|" "$VALUES_YAML"
}
