apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-role
rules:
- apiGroups:
  - ""
  - apps
  - metrics.k8s.io
  - networking.k8s.io
  resources:
  - configmaps
  - deployments
  - ingresses
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - services
  - statefulsets
  verbs:
  - get
  - list
  - watch
