# Deprecated - remove this after all systems have been migrated to use DeltaFiProperties
apiVersion: v1
kind: ConfigMap
metadata:
  name: deltafi-ui-config
data:
  config: |-
    domain: {{ .Values.ingress.domain }}
    title: {{ default "DeltaFi" .Values.deltafi.ui.title }}
    useUTC: {{ default "false" .Values.deltafi.ui.useUTC | quote }}
    authMode: {{ .Values.deltafi.auth.mode | quote }}
{{- if .Values.deltafi.ui.deltaFileLinks }}
    deltaFileLinks:
{{ .Values.deltafi.ui.deltaFileLinks | toYaml | indent 6 }}
{{- end }}
{{- if .Values.deltafi.ui.externalLinks }}
    externalLinks:
{{ .Values.deltafi.ui.externalLinks | toYaml | indent 6 }}
{{- end }}
{{- if .Values.deltafi.ui.topBar }}
    topBar:
{{ .Values.deltafi.ui.topBar | toYaml | indent 6 }}
{{- end }}
{{- if .Values.deltafi.ui.securityBanner }}
    securityBanner:
{{ .Values.deltafi.ui.securityBanner | toYaml | indent 6 }}
{{- end }}
