---
# Deploy a nodemonitor instance per node for node metrics retrieval
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deltafi-nodemonitor
  namespace: deltafi
  labels:
    app: deltafi-nodemonitor
spec:
  selector:
    matchLabels:
      app: deltafi-nodemonitor
  template:
    metadata:
      labels:
        app: deltafi-nodemonitor
    spec:
      serviceAccountName: deltafi-nodemonitor
      terminationGracePeriodSeconds: 1
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: nodemonitor
        image: {{ .Values.deltafi.nodemonitor.image }}
        env:
        {{- include "defaultEnvVars" . | nindent 12 }}
        {{- include "graphiteEnvVars" . | nindent 12 }}
            - name: PERIOD
              value: "{{ .Values.deltafi.nodemonitor.period }}"
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
        volumeMounts:
        - name: pvdata
          mountPath: /data
          readOnly: true
      volumes:
      - name: pvdata
        hostPath:
          path: /data
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deltafi-nodemonitor
subjects:
- kind: ServiceAccount
  name: deltafi-nodemonitor
  namespace: deltafi
roleRef:
  kind: ClusterRole
  name: deltafi-nodemonitor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deltafi-nodemonitor
  namespace: deltafi
subjects:
  - kind: ServiceAccount
    name: deltafi-nodemonitor
    namespace: deltafi
roleRef:
  kind: Role
  name: deltafi-nodemonitor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deltafi-nodemonitor-kubeadm-config
  namespace: deltafi
subjects:
  - kind: ServiceAccount
    name: deltafi-nodemonitor
    namespace: deltafi
roleRef:
  kind: Role
  name: deltafi-nodemonitor-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deltafi-nodemonitor
  labels:
    app: deltafi-nodemonitor
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deltafi-nodemonitor
  # should be the namespace where nodemonitor is running
  namespace: deltafi
  labels:
    app: deltafi-nodemonitor
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deltafi-nodemonitor-kubeadm-config
  namespace: deltafi
  labels:
    app: deltafi-nodemonitor
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - kubeadm-config
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deltafi-nodemonitor
  namespace: deltafi
  labels:
    app: deltafi-nodemonitor
---
