{{- if .Values.deltafi.docs.enabled -}}
# Documentation server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-docs
  labels:
    app: deltafi-docs
    group: deltafi-core
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-docs
      group: deltafi-core
  template:
    metadata:
      labels:
        app: deltafi-docs
        group: deltafi-core
    spec:
      containers:
      - name: deltafi-docs
        image: {{ .Values.deltafi.docs.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: docker-secret
  strategy:
    type: Recreate
{{- end -}}
