apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deltafi-ingress
  annotations:
  {{- include "defaultIngressAnnotations" . | nindent 4 }}
  {{- include "authAnnotations" . | nindent 4 }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.deltafi.ingress.envVar.HTTP_MAX_BODY_SIZE }}
spec:
  {{- if eq .Values.ingress.tls.enabled true }}
  tls:
  - secretName: {{ coalesce .Values.ingress.tls.secrets.ingress .Values.ingress.tls.secrets.default }}
  {{- end }}
  rules:
  - host: ingress.{{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deltafi-ingress-service
            port:
              number: 80
