apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-role
subjects:
- kind: ServiceAccount
  name: deltafi-api
  namespace: deltafi