apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deltafi-auth
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    name: deltafi-auth
