apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deltafi-core-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: core-role
subjects:
  - kind: ServiceAccount
    name: deltafi-core
