{{- if .Values.deltafi.docs.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: deltafi-docs-service
spec:
  selector:
    app: deltafi-docs
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
{{- end -}}
