{{- if and (.Values.deltafi.clickhouse_etl.enabled) (.Values.clickhouse.enabled) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deltafi-clickhouse-etl
  labels:
    app: deltafi-clickhouse-etl
    group: deltafi-core
spec:
  serviceName: clickhouse-etl
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-clickhouse-etl
      group: deltafi-core
  template:
    metadata:
      labels:
        app: deltafi-clickhouse-etl
        group: deltafi-core
    spec:
      {{- include "initContainersWaitForDatabases" . | nindent 6 }}
      containers:
      - name: deltafi-clickhouse-etl
        image: {{ .Values.deltafi.api.image }}
        imagePullPolicy: IfNotPresent
        command: [ 'bundle', 'exec', 'bin/clickhouse_etl.rb' ]
        env:
        - name: RUNNING_IN_CLUSTER
          value: "true"
        - name: ETL_INTERVAL
          value: "{{ .Values.deltafi.clickhouse_etl.interval }}"
        - name: ETL_LAG
          value: "{{ .Values.deltafi.clickhouse_etl.lag }}"
        - name: ETL_BATCH
          value: "{{ .Values.deltafi.clickhouse_etl.batch }}"
        - name: ETL_DELETE_TTL
          value: "{{ .Values.deltafi.clickhouse_etl.delete_ttl }}"
        {{- include "commonEnvVars" . | nindent 8 }}
        {{- include "mongoEnvVars" . | nindent 8 }}
        {{- include "clickhouseEnvVars" . | nindent 8 }}
        - name: PROBE_DIR
          value: "/tmp/probe"
        livenessProbe:
          exec:
            command: ["/monitor_probe.sh"]
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 2
      imagePullSecrets:
      - name: docker-secret
      serviceAccountName: deltafi-clickhouse
      nodeSelector:
        node-role.deltafi.org/compute: "true"
{{- end }}
