# DeltaFi config
deltafi:
  ssl:
    secret: keystore-secret
    passwordSecret: keystore-password-secret
    mountPath: /etc/pki
    protocol: TLSv1.2
    keyStoreName: keyStore.p12
    keyStoreType: PKCS12
    trustStoreName: trustStore.jks
    trustStoreType: JKS
  core_actions:
    image: deltafi/deltafi-core-actions:1.0.0-RC7
  passthrough:
    image: deltafi/deltafi-passthrough:1.0.0-RC7
    enabled: true
  core:
    image: deltafi/deltafi-core:1.0.0-RC7
    mongo_host: deltafi-mongodb
  docs:
    image: deltafi/deltafi-docs:1.0.0-RC7
    enabled: true
  ingress:
    envVar:
      HTTP_MAX_BODY_SIZE: 5G
  auth:
    image: deltafi/deltafi-auth:1.0.0-RC7
    mode: basic # basic, cert, or disabled
    secret: auth-secret
    entityResolver:
      enabled: false
      image: deltafi/deltafi-entity-resolver:1.0.0-RC7
      url: http://127.0.0.1:8080/
  api:
    image: deltafi/deltafi-api:1.0.0-RC7
  ui:
    image: deltafi/deltafi-ui:1.0.0-RC7
  egress_sink:
    enabled: true
    image: deltafi/deltafi-egress-sink:1.0.0-RC7
  nodemonitor:
    image: deltafi/deltafi-nodemonitor:1.0.0-RC7
    envVars:
      - name: GRAPHITE_HOST
        value: deltafi-graphite
      - name: GRAPHITE_PORT
        value: "2003"
      - name: PERIOD
        value: "9"

# Kubernetes ingress config
ingress:
  domain: local.deltafi.org
  tls:
    enabled: false
    secrets:
      default: local-deltafi-org
# MinIO config
minio:
  environment:
    MINIO_API_DELETE_CLEANUP_INTERVAL: 1s
  mode: standalone
  existingSecret: minio-keys
  resources:
    requests:
      memory: 2Gi
  replicas: 1
  persistence:
    enabled: true
    existingClaim: deltafi-minio
  service:
    type: NodePort
  nodeSelector:
    node-role.deltafi.org/storage: "true"
# MongoDB config
mongodb:
  image:
    repository: bitnami/mongodb
    tag: 5.0.14
  architecture: standalone
  useStatefulSet: false
  auth:
    existingSecret: mongodb-passwords
    enabled: true
    database: deltafi
    username: mongouser
  service:
    type: NodePort
  persistence:
    enabled: true
    existingClaim: deltafi-mongodb
  volumePermissions:
    enabled: true
  nodeSelector:
    node-role.deltafi.org/storage: "true"
# Redis config
redis:
  image:
    repository: bitnami/redis
    tag: 7.0.8
  architecture: standalone
  auth:
    existingSecret: redis-password
    enabled: true
  commonConfiguration: |-
    # Diable AOF https://redis.io/topics/persistence#append-only-file
    appendonly no
    # Disable RDB persistence
    save ""
  master:
    persistence:
      enabled: false
    nodeSelector:
      node-role.deltafi.org/compute: "true"
# Kubernetes Dashboard config
kubernetes-dashboard:
  image:
    tag: v2.7.0
  securityContext: null
  metricsScraper:
    enabled: true
    image:
      tag: v1.0.9
  protocolHttp: true
  service:
    externalPort: 80
  settings:
    clusterName: 'DeltaFi'
    itemsPerPage: 50
    labelsLimit: 3
    logsAutoRefreshTimeInterval: 5
    resourceAutoRefreshTimeInterval: 5
    disableAccessDeniedNotifications: false
    defaultNamespace: deltafi
    namespaceFallbackList:
      - default

grafana:
  image:
    repository: deltafi/grafana
    tag: 9.5.2-2
  persistence:
    enabled: true
    existingClaim: deltafi-grafana
  nodeSelector:
    node-role.deltafi.org/storage: "true"
  grafana.ini:
    auth.anonymous:
      enabled: false
    auth.basic:
      enabled: false
    auth.proxy:
      enabled: true
      header_name: X-User-Name
      headers: Role:X-Metrics-Role
      auto_sign_up: true
    analytics:
      reporting_enabled: false
      check_for_updates: false
      check_for_plugin_updates: false
      enable_feedback_links: false
    dashboards:
      min_refresh_interval: "10s"
    log:
      mode: console
    log.console:
      format: json
    unified_alerting:
      enabled: true
    alerting:
      enabled: false
    security:
      allow_embedding: true
  sidecar:
    dashboards:
      enabled: true
      provider:
        folder: "DeltaFi"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Graphite
        type: graphite
        access: proxy
        url: http://deltafi-graphite:8080
        editable: false
        isDefault: true
        version: 2
        uid: deltafi-graphite
      - name: Loki
        type: loki
        access: proxy
        url: http://deltafi-loki:3100
        editable: false
        isDefault: false
        version: 2
        uid: deltafi-loki
promtail:
  image:
    tag: 2.8.0
  persistence:
    enabled: true
    existingClaim: deltafi-promtail
  config:
    clients:
      - url: http://deltafi-loki:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - cri: {}
        - labeldrop:
            - filename
        # Label action logs
        - match:
            selector: '{ app=~".+" } |~ "\"action\":\"[^\"]+\""'
            stages:
            - json:
                expressions:
                  action: action
            - labels:
                action:
            - static_labels:
                type: 'ACTION'
        # Remove noisy probe logs
        - match:
            selector: '{app="deltafi-ui"}'
            stages:
              - drop:
                  expression: "probe"
        # Label audit logs
        - match:
              selector: '{ app=~".*" } |= "\"loggerName\":\"AUDIT\""'
              stages:
              - json:
                  expressions:
                    user: user
              - labels:
                  user:
              - static_labels:
                  type: "AUDIT"
        # Categorize UI HTTP status codes
        - match:
              selector: '{ app="deltafi-ui" } |= " 200 "'
              stages:
              - static_labels:
                  level: "DEBUG"
        - match:
              selector: '{ app="deltafi-ui" } |= " 304 "'
              stages:
              - static_labels:
                  level: "DEBUG"
        - match:
              selector: '{ app="deltafi-ui" } |= " 404 "'
              stages:
              - static_labels:
                  level: "ERROR"
        - match:
              selector: '{ app="deltafi-ui" } |= " 500 "'
              stages:
              - static_labels:
                  level: "ERROR"
        - match:
              selector: '{ app="deltafi-ui" } |= " 503 "'
              stages:
              - static_labels:
                  level: "ERROR"
        # Categorize API HTTP status codes
        - match:
              selector: '{ app="deltafi-api" } |= " 200 "'
              stages:
              - static_labels:
                  level: "DEBUG"
        - match:
              selector: '{ app="deltafi-api" } |= " 404 "'
              stages:
              - static_labels:
                  level: "ERROR"
        - match:
              selector: '{ app="deltafi-api" } |= " 500 "'
              stages:
              - static_labels:
                  level: "ERROR"
        - match:
              selector: '{ app="deltafi-api" } |= " 503 "'
              stages:
              - static_labels:
                  level: "ERROR"
        # Squelch/categorize mongodb noise
        - match:
              selector: '{ app="mongodb" }'
              stages:
                - drop:
                    expression: "Connection accepted|Connection ended|client metadata"
        - match:
              selector: '{ app="mongodb" } |= "WiredTiger message"'
              stages:
              - static_labels:
                  level: "DEBUG"
        - match:
              selector: '{ app="mongodb" } |= "Slow query"'
              stages:
              - static_labels:
                  level: "DEBUG"
        # Squelch nasty graphite debug logs
        - match:
            selector: '{app="graphite"}'
            stages:
              # Filtering out graphite debug logs containing "(Tagging|Tagged)"
              - drop:
                  expression: "Tagg"
        # Clear out excessive debug messages
        - match:
            selector: '{app="deltafi-monitor"}'
            stages:
              - drop:
                  expression: "DEBUG"
        # Clear out excessive post messages
        - match:
            selector: '{app="deltafi-egress-sink"}'
            stages:
              - drop:
                  expression: "POST / HTTP"
        # Clear out excessive probe messages
        - match:
            selector: '{app="kubernetes-dashboard"}'
            stages:
              - drop:
                  expression: "kube-probe"
              - drop:
                  expression: "/healthz"
loki:
  image:
    tag: 2.8.0
  persistence:
    enabled: true
    existingClaim: deltafi-loki
  nodeSelector:
    node-role.deltafi.org/storage: "true"
  extraArgs:
    log.level: warn
  config:
    compactor:
      retention_enabled: true
      retention_delete_delay: 10m
      compaction_interval: 10m
      retention_delete_worker_count: 150
    limits_config:
      retention_period: 744h
      retention_stream:
      - selector: '{level="DEBUG"}'
        priority: 1
        period: 24h
      - selector: '{container="deltafi-ingress",type="AUDIT"}'
        priority: 3
        period: 24h
      - selector: '{container="deltafi-monitor"}'
        priority: 4
        period: 96h
      - selector: '{container="mongodb"}'
        priority: 5
        period: 168h
      - selector: '{app="kubernetes-dashboard"}'
        priority: 6
        period: 96h
      - selector: '{app="grafana"}'
        priority: 7
        period: 168h
    query_scheduler:
      max_outstanding_requests_per_tenant: 500
  livenessProbe:
   initialDelaySeconds: 5
  readinessProbe:
   initialDelaySeconds: 5

# Graphite Configuration
graphite:
  image:
    tag: 1.1.10-4
  persistence:
    enabled: true
    existingClaim: deltafi-graphite
  nodeSelector:
    node-role.deltafi.org/storage: "true"
  statsd:
    interface: TCP

docker-registry:
  enabled: false
  image:
    tag: 2.8.1
  persistence:
    enabled: true
    existingClaim: deltafi-docker-registry
  serviceAccount:
    create: true
  garbageCollect:
    enabled: true
    schedule: "0 * * * *"

registry-ui:
  enabled: false
  registryHost: deltafi-docker-registry
